"""Update Treatment

Revision ID: b10f5310a847
Revises: f82bb1f156ef
Create Date: 2026-01-24 20:53:27.999110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10f5310a847'
down_revision = 'f82bb1f156ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.alter_column('appointment_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.alter_column('appointment_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
