"""added new column password in doc&pat

Revision ID: b533d6c02760
Revises: 
Create Date: 2026-01-15 12:56:42.639207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b533d6c02760'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_password', sa.String(length=16), nullable=True))

    op.execute("UPDATE doctor SET doc_password = 'changeme'")

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.alter_column('doc_password', nullable=False)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pat_password', sa.String(length=16), nullable=True))

    op.execute("UPDATE patient SET pat_password = 'changeme'")

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('pat_password', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('pat_password')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('doc_password')

    # ### end Alembic commands ###
