"""adding column

Revision ID: f82bb1f156ef
Revises: b533d6c02760
Create Date: 2026-01-23 14:48:25.535177
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f82bb1f156ef'
down_revision = 'b533d6c02760'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_appointment_availability_id',  # Constraint name
            'doctor_availability',
            ['availability_id'],
            ['id']
        )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointment_availability_id', type_='foreignkey')
        batch_op.drop_column('availability_id')
    # ### end Alembic commands ###
